In [0]:
import numpy as np

# 배열 변환하기
# 전치, shape변환, 요소추가, 결합, 분리 등 지원

# 배열 전치transpose
# 배열객체.T
# 배열의 axis가 바뀜

a = np.arange(9).reshape(3,3)
print(a)
print(a.T)
print()

b = np.arange(24).reshape(4,6)
print(b)
print(b.T)
print()

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[0 3 6]
 [1 4 7]
 [2 5 8]]

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]
[[ 0  6 12 18]
 [ 1  7 13 19]
 [ 2  8 14 20]
 [ 3  9 15 21]
 [ 4 10 16 22]
 [ 5 11 17 23]]



In [0]:
# 배열의 shape변환
# ravel : 배열을 1차원 형태로 변경. 결과가 원본 대비 뷰이므로 특정 위치 값 수정 시 원본의 해당되는 값도 같이 변경
# reshape : 배열의 shape을 지정한 형태로 변경

In [0]:
c = np.arange(100, 91, -1).reshape(3,3)
d = c.ravel()
print(c)
print(d)
print(c)

[[100  99  98]
 [ 97  96  95]
 [ 94  93  92]]
[100  99  98  97  96  95  94  93  92]
[[100  99  98]
 [ 97  96  95]
 [ 94  93  92]]


In [0]:
d[::2] = 0
print(d)
print(c) #원본인 2차원 배열의 내용도 변경됨

[ 0 99  0 97  0 95  0 93  0]
[[ 0 99  0]
 [97  0 95]
 [ 0 93  0]]


In [11]:
e = np.arange(24).reshape(4,6)
print(e)
print()

f = e.reshape(3,4,2) #2차원 배열을 3차원으로
print(f)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]

[[[ 0  1]
  [ 2  3]
  [ 4  5]
  [ 6  7]]

 [[ 8  9]
  [10 11]
  [12 13]
  [14 15]]

 [[16 17]
  [18 19]
  [20 21]
  [22 23]]]


In [13]:
# 배열크기 변경
# np.resize(대상, 크기)
# 배열의 요소 수 에 변화? resize는 reshape과 형상을 바꿀 수 있다는 측면에서는 동일하지만 요소 수에 변화를 줄 수 있는 것은 resize임

import numpy as np
import matplotlib.pyplot as plt

# 요소 수가 동일한 resize
g = np.random.randint(1,10, (2,6))
print(g)

g.resize((6,2)) # 2x6 => 6x2 배열로 수정
print(g)

# 요소 수가 변하는 resize (늘어남)
h = np.random.randint(1,50, (2,6))
print(h)

h.resize(4,6) # 2x6 => 4x6 배열로 수정
print(h) # 늘어난 요소는 0으로 채워짐

# 요소 수가 변화는 resize (줄어듬)
i = np.random.randint(1,5, (4,6))
print(i)

i.resize(2,6) # 4x6 => 2x6 배열로 수정
print(i) #줄어든 요소는 제외

# 위에 한 거 resize가 아닌, reshape으로 해보기 (아래 오류 뜸. 요소 수 줄이거나 늘이면서 형상 바꾸려면 resize()가 정답임)
i = np.random.randint(1,5, (4,6))
print(i)
i.reshape(2,6) # 오류 발생!!
print(i)

[[3 1 9 3 1 6]
 [8 6 2 5 9 7]]
[[3 1]
 [9 3]
 [1 6]
 [8 6]
 [2 5]
 [9 7]]
[[25  2 16 34 48 15]
 [ 5  8 33 35 12 47]]
[[25  2 16 34 48 15]
 [ 5  8 33 35 12 47]
 [ 0  0  0  0  0  0]
 [ 0  0  0  0  0  0]]
[[2 1 2 3 2 1]
 [3 3 4 3 2 3]
 [4 2 3 1 3 1]
 [4 2 1 3 4 2]]
[[2 1 2 3 2 1]
 [3 3 4 3 2 3]]
[[3 1 2 3 4 4]
 [1 1 2 2 2 2]
 [2 1 3 1 1 2]
 [1 1 1 4 2 2]]


ValueError: ignored

In [53]:
# 배열에 요소 추가
# np.append(대상, 내용, 추가방향) <- 단, concatenate()과 다르게 대상 2개만 붙일 수 있음
# 배열의 끝에 내용이 추가!

j = np.arange(1,10).reshape(3,3)
k = np.arange(9,0,-1).reshape(3,3)
t = np.arange(1,4).reshape(1,3)
y = np.arange(1,10).reshape(3,3)

print(j)
print(k)
print(t)
print()

# axis를 지정하지 않았을 때
l = np.append(j, k)
print(l) # 1차원 배열로 변환되어 추가됨
print()

l = np.append(j, np.append(k,y)) # 이렇게 하면 결국 3개 대상 결합 효과이긴 하겠으나
print(l) # 1차원 배열로 변환되어 추가됨
print()

l = np.append(j, t)
print(l) # 1차원 배열로 변환되어 추가됨
print()

# axis = 0 으로 설정 시 : 행 단위 추가
l = np.append(j, k, axis=0)
print(l) # 각각 3x3 형태를 유지하며 결합하되, 열의 shape 유지하며 결합 => 기 3x3에서 6x3이 됨
print('shape => ', l.shape)
print()

l = np.append(j, t, axis=0) #이렇게 서로 형태가 다른 것을 append 시 broadcast 안됨
print(l) # 각각 3x3 형태를 유지하며 결합하되, 열의 shape 유지하며 결합 => 기 3x3에서 6x3이 됨
print('shape => ', l.shape)
print()


# axis = 1 로 설정 시 : 열 단위 추가
l = np.append(j, k, axis=1)
print(l) # 각각 3x3 형태를 유지하며 결합하되, 행의 shape 유지하며 결합 => 기 3x3에서 3x6이 됨
print('shape => ', l.shape)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[9 8 7]
 [6 5 4]
 [3 2 1]]
[[1 2 3]]

[1 2 3 4 5 6 7 8 9 9 8 7 6 5 4 3 2 1]

[1 2 3 4 5 6 7 8 9 9 8 7 6 5 4 3 2 1 1 2 3 4 5 6 7 8 9]

[1 2 3 4 5 6 7 8 9 1 2 3]

[[1 2 3]
 [4 5 6]
 [7 8 9]
 [9 8 7]
 [6 5 4]
 [3 2 1]]
shape =>  (6, 3)

[[1 2 3]
 [4 5 6]
 [7 8 9]
 [1 2 3]]
shape =>  (4, 3)

[[1 2 3 9 8 7]
 [4 5 6 6 5 4]
 [7 8 9 3 2 1]]
shape =>  (3, 6)


In [30]:
# 배열에 요소 추가
# np.insert(대상, 위치, 내용, 추가방향)
# 배열의 특정위치에 내용이 추가됨

m = np.random.randint(1,46, (3,3))
print(m)
print()

# axis를 지정하지 않았을 때
n = np.insert(m, 3, 999)
print(n) # 1차원 배열로 변환되어 추가됨
print()

# axis = 0 으로 설정 시 : 행 단위 추가
n = np.insert(m, 2, 999, axis=0)
print(n) # 추가되는 요소로 인해 나머지는 밀림 => 기 3x3에서 4x3이 됨
print('shape => ', n.shape)
print()

# axis = 1 로 설정 시 : 열 단위 추가
n = np.insert(m, 2, 999, axis=1)
print(n) # 추가되는 요소로 인해 나머지는 밀림 => 기 3x3에서 3x4가 됨
print('shape => ', n.shape)

[[43 38 23]
 [21 27 25]
 [29 33 37]]

[ 43  38  23 999  21  27  25  29  33  37]

[[ 43  38  23]
 [ 21  27  25]
 [999 999 999]
 [ 29  33  37]]
shape =>  (4, 3)

[[ 43  38 999  23]
 [ 21  27 999  25]
 [ 29  33 999  37]]
shape =>  (3, 4)


In [33]:
# 배열의 요소 삭제
# np.delete(대상, 위치, 삭제방향)
# 배열의 특정위치 내용이 삭제

m = np.random.randint(1,46, (3,3))
print(m)
print()

# axis를 지정하지 않았을 때
n = np.delete(m, 2)
print(n) # 1차원 배열로 변환되어 삭제됨
print()

# axis = 0 으로 설정 시 : 행 단위 삭제
n = np.delete(m, 2, axis=0)
print(n) # 삭제되는 요소로 인해 나머지 줄어듬 => 기 3x3에서 2x3이 됨
print('shape => ', n.shape)
print()

# axis = 1 로 설정 시 : 열 단위 삭제
n = np.delete(m, 2, axis=1)
print(n) # 삭제되는 요소로 인해 나머지는 줄어듬 => 기 3x3에서 3x2가 됨
print('shape => ', n.shape)

[[ 7  1 21]
 [10 30 30]
 [37 44 45]]

[ 7  1 10 30 30 37 44 45]

[[ 7  1 21]
 [10 30 30]]
shape =>  (2, 3)

[[ 7  1]
 [10 30]
 [37 44]]
shape =>  (3, 2)


In [55]:
# 배열 집합
# np.concatenate(대상1, 대상2, ...), 결합방향)
o = np.arange(1,7).reshape(2,3)
p = np.arange(9,3,-1).reshape(2,3)
print(o)
print(p)
print()

# axis 생략 시 => axis = 0 : 행 단위 결합
q = np.concatenate([o,p])
print(q)

# axis = 0 으로 지정 시 위와 동일

# axis = 1로 지정
q = np.concatenate([o,p], axis=1)
print(q)



[[1 2 3]
 [4 5 6]]
[[9 8 7]
 [6 5 4]]

[[1 2 3]
 [4 5 6]
 [9 8 7]
 [6 5 4]]
[[1 2 3 9 8 7]
 [4 5 6 6 5 4]]


In [62]:
# np.concatenate의 간략화 버전
# np.hstack(대상들)
# np.vstack(대상들)

s = np.random.randint(1,45, (2,3))
t = np.random.randint(1,45, (2,3))
u = np.random.randint(1,45, (2,3))
print(s)
print(t)
print(u)
print()

l = np.hstack([s,t,u])
print(l)
print()

l = np.vstack([s,t,u])
print(l)

[[17  1  2]
 [21 43 27]]
[[20 41  6]
 [31  8 25]]
[[ 3 43 22]
 [42 24 11]]

[[17  1  2 20 41  6  3 43 22]
 [21 43 27 31  8 25 42 24 11]]

[[17  1  2]
 [21 43 27]
 [20 41  6]
 [31  8 25]
 [ 3 43 22]
 [42 24 11]]


In [74]:
# 배열 나누기
# np.hsplit(대상, 갯수)
# np.vsplit(대상, 갯수)
# 배열을 나눌 시 갯수 또는 indexing/slicing을 이용할 수 있음

v = np.arange(1,25).reshape(4,6)
print(v)
print()

# 배열 수평분할 : 열 기준으로 나눔
w = np.hsplit(v,2)
print(w)
w = np.hsplit(v,3)
print(w)
print()


# 배열 수직분할 : 행 기준으로 나눔
w = np.vsplit(v,2)
print(w)
#w = np.vsplit(v,3) # 3개 각각이 요소 수가 달라 equal division이 안된다는 오류 뜸!! 즉, 균일하게 나눠야 함
#print(w)
w = np.vsplit(v,4)
print(w)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]]

[array([[ 1,  2,  3],
       [ 7,  8,  9],
       [13, 14, 15],
       [19, 20, 21]]), array([[ 4,  5,  6],
       [10, 11, 12],
       [16, 17, 18],
       [22, 23, 24]])]
[array([[ 1,  2],
       [ 7,  8],
       [13, 14],
       [19, 20]]), array([[ 3,  4],
       [ 9, 10],
       [15, 16],
       [21, 22]]), array([[ 5,  6],
       [11, 12],
       [17, 18],
       [23, 24]])]

[array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]]), array([[13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24]])]
[array([[1, 2, 3, 4, 5, 6]]), array([[ 7,  8,  9, 10, 11, 12]]), array([[13, 14, 15, 16, 17, 18]]), array([[19, 20, 21, 22, 23, 24]])]
